### ISSUE TITLE
Proposte finali di stack

### ISSUE THREAD

**Issue by Kawika13** [kerbless/newseful#11]
Scegliere per filo e per segno gli strumenti che verranno utilizzati all'interno del stack.

**Comment by kerbless** [comment]
https://enkonix.com/blog/web-development-stacks/

**Comment by kerbless** [comment]
Visti gli sviluppi del programma scolastico e la volontà di mantenersi in linea con esso per ottimizzare i tempi, propongo come stack finale per il back-end il classico stack LAMP (pur tenendo in considerazione che la ricerca ha prodotto risultati interessanti che potrebbero essre usati in seguito).
Per quanto riguarda il front-end, a parte i classici HTML, CSS e JS, consiglio a @Junjuji l'utilizzo di TailwindCSS e/o SCSS ma anche questi rimangono a sua discrezione.
Per quanto riguarda il production environment, continueremo ad usare sia Vercel che Netlify senza grandi modifiche alle impostazioni di default e lasceremo spazio ad eventuali modifiche nella fase finale del progetto.
