### ISSUE TITLE
Test sulle richieste all'API

### ISSUE THREAD

**Issue by Kawika13** [kerbless/newseful#13]
Effettuare prime richieste all'API NewsAPI così da poter effettivamente vedere le differenze tra linguaggio e linguaggio. Fatto ciò, scegliere il linguaggio più opportuno.

**Comment by Marcooone** [comment]
Ho effettuato le prime richieste all'API usando la Key ottenuta dal sito di "NewsAPI" tramite il linguaggio Node.js, dove tramite una richiesta AJAX (https://www.geekandjob.com/wiki/ajax) e una semplice pagina HTML si effettua la richiesta. Le informazioni richieste, successivamente verranno mostrate sullo schermo in maniera disordinata e poco comprensibile, che dovranno poi essere gestite dal FRONT-END. 
Per quanto riguarda gli altri linguaggi di programmazione ho provato solo il php, ma non essendo riuscito ad ottenere nessun risultato, propongo di utilizzare Node.js anche per la sua semplicità nell'effettuare la richiesta.
