### ISSUE TITLE
Test lato Back-End User

### ISSUE THREAD

**Issue by Kawika13** [kerbless/newseful#14]
Effettuare dei test, decontestualizzati dal progetto finale, che vedranno una form di registrazione e un'altra di login. Interfacciarsi con il tecnico di front-end per formalizzare la parte grafica del test.

**Comment by kerbless** [comment]
Nello sviluppo di un sistema di login ho incontrato una scelta di sviluppo: per effettuare la connessione tra PHP e il database sono disponibili due diverse API.
Vedi: https://websitebeaver.com/php-pdo-vs-mysqli
Nel programma scolastico stiamo affrontando l'argomento utilizzando MySQLi, nello sviluppo di questo progetto cercherò di utilizzare PDO anche per accrescimento personale.

**Comment by kerbless** [comment]
# N.B.
Per completare questa task/issue parte del lavoro non è visibile nei commit in quanto riguarda la configurazione (manuale) del backend di Apache, PHP e MySQL.

(current testing environment: Arch Linux 6.0.8-arch1-1)

**Comment by kerbless** [comment]
95dbf50401a0b21cfc703934dc993118767dc21b closes
